import * as Localization from 'expo-localization';
import i18n from 'i18n-js';

// Set the key-value pairs for the different languages you want to support.
i18n.translations = {
    en: {
        term_text_tns: 'Term Not Started',
        term_text_fhot: 'First half of term in progress',
        term_text_shot: 'Second half of term in progress',
        term_text_eot: 'End of Term',
        error_text_nodata: 'No Data',
        attendance_text_excused: 'Excused',
        attendance_text_nonexcused: 'Non-Excused',
        attendance_text_nurseroom: 'Nurse Room',
        attendance_text_sportsevent: 'Sports Event',
        attendance_text_fieldtrip: 'Field Trip',
        attendance_text_late: 'Late',
        attendance_text_absent: 'Absent',
        home_title: 'Home',
        message_title: 'Message',
        academics_title: 'Academics',
        studentlife_title: 'Student Life',
        bodwellexplained_title: 'Bodwell Explained',
        schoolcommunity_title: 'School Community',
        setting_title: 'Settings',
        logout_title: 'Logout',
        home_header: 'Home',
        message_header: 'Message',
        messagedetail_header: 'Message',
        academics_header: 'Academics',
        academics_button_attendance: 'Attendance',
        attendance_header: 'Attendance',
        attendance_text_attendancereport: 'ATTENDANCE REPORT',
        academics_text_creditcourse: 'Credit Course',
        academics_text_teacher: 'Teacher',
        academics_text_noncreditcourses: 'Non-Credit Courses',
        academics_text_saturdayenrichment: 'Saturday Enrichment',
        academics_text_club: 'Club',
        academicdetail_header: 'Academic Detail',
        academicdetail_text_overallaverage: 'Overall Average',
        academicdetail_text_grade: 'Grade',
        academicdetail_text_teacher: 'TEACHER',
        academicdetail_text_categoryweight: 'Category Weight',
        academicdetail_text_vci: 'View Category Item',
        academicdetail_text_earnedpoint: 'Earned Point',
        academicdetail_text_earnedpercentage: 'Earned Percentage',
        academicdetail_text_attendancereport: 'Attendance Report',
        academicdetail_text_categoryitems: 'Category Items',
        studentlife_header: 'Student Life',
        studentlife_text_participationhours: 'PARTICIPATION HOURS',
        studentlife_text_tpic: 'Total Participations In Current Term',
        studentlife_text_qfce: 'Qualified for Career Exploration',
        studentlife_text_hrs: 'Hrs',
        studentlife_text_pore: 'Physical, Outdoor & Recreation Education',
        studentlife_text_aisd: 'Academic, Interest & Skill Development',
        studentlife_text_cile: 'Citizenship, Interaction & Leadership Experience',
        studentlife_text_acle: 'Arts, Culture & Local Exploration',
        studentlife_button_mcai: 'My Child\'s Activities In',
        studentlife_button_asai: 'All School Activities In',
        studentlife_button_tphs: 'Total Participation Hours Since',
        volunteerhours_header: 'Volunteer Hours',
        volunteerhours_text_ceh: 'CAREER EXPLORATION HOURS',
        volunteerhours_text_qfce: 'Qualified for Career Exploration',
        volunteerhours_text_hrs: 'hrs',
        studentlifedetail_header: 'Student Life Detail',
        studentlifedetail_text_hrs: 'hrs',
        studentlifedetail_text_pore: 'Physical, Outdoor & Recreation Education',
        studentlifedetail_text_aisd: 'Academic, Interest & Skill Development',
        studentlifedetail_text_cile: 'Citizenship, Interaction & Leadership Experience',
        studentlifedetail_text_acle: 'Arts, Culture & Local Exploration',
        mychildsactivities_header: 'My Child\'s Activities',
        mychildsactivities_text_cua: 'Complete / Upcoming Activities',
        allactivities_header: 'All Activities',
        allactivities_text_allactivities: 'All Activities',
        activitydetail_header: 'Activity Detail',
        activitydetail_text_teacher: 'TEACHER',
        activitydetail_text_eph: 'Earned Participation Hours',
        activitydetail_text_vwe: 'Volunteer & Work Experience',
        activitydetail_text_location: 'Location',
        activitydetail_text_from: 'From',
        activitydetail_text_to: 'To',
        participationgraph_header: 'Participation Graph',
        participationgraph_text_currentterm: 'Current Term',
        participationgraph_text_totalhours: 'Total Hours',
        participationgraph_text_participationhours: 'Participation Hours',
        participationgraph_text_tph: 'Total Participation Hours',
        participationgraph_text_since: 'Since',
        bodwellexplained_header: 'Bodwell Explained',
        bodwellexplained_text_lab: 'LEARN ABOUT BODWELL',
        bodwellexplained_text_avlt: 'A video library to help answer some of the most commonly asked questions',
        bodwellexplained_text_academics: 'ACADEMICS',
        bodwellexplained_text_studentlife: 'STUDENT LIFE',
        bodwellexplained_text_video: 'Video',
        bodwellexplainedlist_header: 'Bodwell Explained',
        bodwellexplainedlist_text_academicsvideo: 'ACADEMICS VIDEO',
        bodwellexplainedlist_text_slv: 'STUDENT LIFE VIDEO',
        schoolcommunity_header: 'School Community',
        schoolcommunity_text_wgo: 'WHAT\'S GOING ON?',
        schoolcommunity_text_ambb: 'A multi-media bulletin board to keep you up to date with all that goes on at Bodwell',
        schoolcommunity_text_cd: 'CALENDAR & DATES',
        schoolcommunity_text_biv: 'BODWELL IN VIDEO',
        schoolcommunity_text_picturegallery: 'PICTURE GALLERY',
        schoolcommunity_text_wvm: 'WEEKLY VIDEO MESSAGE',
        schoolcommunity_text_staffinvolved: 'STAFF INVOLVED',
        schoolcommunity_text_importantdocuments: 'IMPORTANT DOCUMENTS',
        calendar_header: 'Calendar',
        bodwellinvideo_header: 'Bodwell In Video',
        picturegallery_header: 'Picture Gallery',
        picturegallery_text_picturegallery: 'PICTURE GALLERY',
        picturegallery_text_pavg: 'Photo and video galleries of the campus and events here at Bodwell. Check back often for updates!',
        picturegallery_text_campusphotos: 'CAMPUS PHOTOS',
        picturegallery_text_studentlife: 'STUDENT LIFE',
        picturegallery_text_btw: 'BODWELL THIS WEEK',
        picturegallery_text_bodwellbruins: 'BODWELL BRUINS',
        campusphotogallery_header: 'Campus Photo',
        studentlifegallery_header: 'Student Life',
        bodwellthisweekgallery_header: 'Bodwell This Week',
        bodwellbruinsgallery_header: 'Bodwell Bruins',
        weeklyvideomessages_header: 'Weekly Video Messages',
        weeklyvideomessagesdetail_text_wvm: 'Weekly Video Messages',
        staffinvolved_header: 'Staff Involved',
        staffinvolved_text_staffinvolved: 'STAFF INVOLVED',
        staffinvolved_text_teachers: 'Teachers',
        staffinvolved_text_sc: 'Saturday-E & Clubs',
        staffinvolved_text_cya: 'Counsellor & Youth Advisors',
        staffinvolved_text_principals: 'Principals',
        importantdocuments_header: 'Documents',
        importantdocuments_text_bsh: 'Bodwell Student Handbook',
        setting_text_language: 'Language',
        setting_text_sypl: 'Set your preferred language in app',

    },
    ja: {
        term_text_tns: '学期開始前',
        term_text_fhot: '前期',
        term_text_shot: '後期',
        term_text_eot: '学期終了',
        error_text_nodata: '該当データがありません',
        attendance_text_excused: '公認',
        attendance_text_nonexcused: '非公認',
        attendance_text_nurseroom: '保健室',
        attendance_text_sportsevent: 'スポーツイベント',
        attendance_text_fieldtrip: 'フィールドトリップ',
        attendance_text_late: '遅刻',
        attendance_text_absent: '欠席',
        home_title: 'ホーム',
        message_title: 'メッセージ',
        academics_title: '授業',
        studentlife_title: '学生生活',
        bodwellexplained_title: 'ボドウェル説明ビデオ',
        schoolcommunity_title: 'コミュニティ',
        setting_title: '設定',
        logout_title: 'ログアウト',
        home_header: 'ホーム',
        message_header: 'メッセージ',
        messagedetail_header: 'メッセージ',
        academics_header: '学科',
        academics_button_attendance: '出欠',
        attendance_header: '出欠',
        attendance_text_attendancereport: '出欠レポート',
        academics_text_creditcourse: '単位認定科目',
        academics_text_teacher: '教師',
        academics_text_noncreditcourses: '単位がない科目',
        academics_text_saturdayenrichment: '土曜日プログラム',
        academics_text_club: '課外クラブ',
        academicdetail_header: '授業詳細',
        academicdetail_text_overallaverage: '全体平均',
        academicdetail_text_grade: '成績',
        academicdetail_text_teacher: '教師',
        academicdetail_text_categoryweight: 'カテゴリー比率',
        academicdetail_text_vci: 'カテゴリーアイテム',
        academicdetail_text_earnedpoint: '獲得ポイント',
        academicdetail_text_earnedpercentage: '獲得ポイント比率',
        academicdetail_text_attendancereport: '出欠状況',
        academicdetail_text_categoryitems: 'カテゴリーアイテム',
        studentlife_header: '学生生活',
        studentlife_text_participationhours: '課外活動時間',
        studentlife_text_tpic: '今期の合計活動時間',
        studentlife_text_qfce: 'キャリア教育関係',
        studentlife_text_hrs: '時間',
        studentlife_text_pore: '体育、アウトドア、レクリエーション関係',
        studentlife_text_aisd: 'アカデミック、スキルアップ関係',
        studentlife_text_cile: '校外活動・リーダーシップ関係',
        studentlife_text_acle: '芸術、文化関係',
        studentlife_button_mcai: '参加したアクティビティー',
        studentlife_button_asai: '全てのスクールアクティビティー',
        studentlife_button_tphs: '合計活動時間',
        volunteerhours_header: 'ボランティア活動時間',
        volunteerhours_text_ceh: 'キャリア教育時間',
        volunteerhours_text_qfce: 'キャリア教育関係',
        volunteerhours_text_hrs: '時間',
        studentlifedetail_header: '学生生活詳細',
        studentlifedetail_text_hrs: '時間',
        studentlifedetail_text_pore: '体育、アウトドア、レクリエーション関係',
        studentlifedetail_text_aisd: 'アカデミック、スキルアップ関係',
        studentlifedetail_text_cile: '校外活動・リーダーシップ関係',
        studentlifedetail_text_acle: '芸術、文化関係',
        mychildsactivities_header: '参加したアクティビティー',
        mychildsactivities_text_cua: '完了済 / 近日中にあるアクティビティー',
        allactivities_header: '全ての活動',
        allactivities_text_allactivities: '全ての活動',
        activitydetail_header: 'アクティビティー詳細',
        activitydetail_text_teacher: '教師',
        activitydetail_text_eph: '活動時間累計',
        activitydetail_text_vwe: 'ボランティア活動時間',
        activitydetail_text_location: '場所',
        activitydetail_text_from: '開始',
        activitydetail_text_to: '終了',
        participationgraph_header: '活動時間表',
        participationgraph_text_currentterm: '今学期',
        participationgraph_text_totalhours: '合計時間',
        participationgraph_text_participationhours: '活動時間',
        participationgraph_text_tph: '合計活動時間',
        participationgraph_text_since: 'から',
        bodwellexplained_header: 'ボドウェルについて',
        bodwellexplained_text_lab: 'ボドウェルについて',
        bodwellexplained_text_avlt: 'よくあるご質問についてビデオの中でお答えします。',
        bodwellexplained_text_academics: '授業',
        bodwellexplained_text_studentlife: '生活',
        bodwellexplained_text_video: 'ビデオ',
        bodwellexplainedlist_header: 'ボドウェル説明ビデオ',
        bodwellexplainedlist_text_academicsvideo: '授業について',
        bodwellexplainedlist_text_slv: '学生生活について',
        schoolcommunity_header: 'スクールコミュニティ',
        schoolcommunity_text_wgo: '最新情報',
        schoolcommunity_text_ambb: 'ボドウェルの最新情報を発信するための様々なコンテンツ',
        schoolcommunity_text_cd: 'カレンダー',
        schoolcommunity_text_biv: 'ビデオ',
        schoolcommunity_text_picturegallery: '写真ギャラリー',
        schoolcommunity_text_wvm: '今週のビデオメッセージ',
        schoolcommunity_text_staffinvolved: '担当スタッフ紹介',
        schoolcommunity_text_importantdocuments: '重要書類',
        calendar_header: 'カレンダー',
        bodwellinvideo_header: 'ビデオ',
        picturegallery_header: '写真ギャラリー',
        picturegallery_text_picturegallery: '写真ギャラリー',
        picturegallery_text_pavg: 'キャンパスやイベントの写真・ビデオギャラリー',
        picturegallery_text_campusphotos: 'キャンパス写真',
        picturegallery_text_studentlife: '学校生活',
        picturegallery_text_btw: '今週のボドウェル',
        picturegallery_text_bodwellbruins: 'ボドウェルブルーインズ',
        campusphotogallery_header: 'キャンパス写真',
        studentlifegallery_header: '学校生活',
        bodwellthisweekgallery_header: '今週のボドウェル',
        bodwellbruinsgallery_header: 'ボドウェルブルーインズ',
        weeklyvideomessages_header: '今週のビデオメッセージ',
        weeklyvideomessagesdetail_text_wvm: '今週のビデオメッセージ',
        staffinvolved_header: '担当スタッフ紹介',
        staffinvolved_text_staffinvolved: '担当スタッフ紹介',
        staffinvolved_text_teachers: '教師',
        staffinvolved_text_sc: '土曜日プログラム & クラブ',
        staffinvolved_text_cya: 'カウンセラー & 寮アドバイザー',
        staffinvolved_text_principals: '校長',
        importantdocuments_header: '書類',
        importantdocuments_text_bsh: 'ボドウェル学生ハンドブック',
        setting_text_language: '言語',
        setting_text_sypl: 'お好みの言語を選択してください。',

    },
    zhHans: {
        term_text_tns: '学期未开始',
        term_text_fhot: '上半学期',
        term_text_shot: '下半学期',
        term_text_eot: '期终',
        error_text_nodata: '没有数据',
        attendance_text_excused: '请假',
        attendance_text_nonexcused: '未请假',
        attendance_text_nurseroom: '校医',
        attendance_text_sportsevent: '体育赛事',
        attendance_text_fieldtrip: '出游',
        attendance_text_late: '迟到',
        attendance_text_absent: '缺勤',
        home_title: '主页',
        message_title: '消息',
        academics_title: '学术',
        studentlife_title: '生活',
        bodwellexplained_title: '关于博域',
        schoolcommunity_title: '博域社区',
        setting_title: '设置',
        logout_title: '登出',
        home_header: '主页',
        message_header: '消息',
        messagedetail_header: '消息',
        academics_header: '学术',
        academics_button_attendance: '出勤',
        attendance_header: '出勤',
        attendance_text_attendancereport: '出勤报告',
        academics_text_creditcourse: '学分课程',
        academics_text_teacher: '老师',
        academics_text_noncreditcourses: '非学分课程',
        academics_text_saturdayenrichment: '周六课程',
        academics_text_club: '社团',
        academicdetail_header: '学术信息',
        academicdetail_text_overallaverage: '总平均分',
        academicdetail_text_grade: '成绩',
        academicdetail_text_teacher: '老师',
        academicdetail_text_categoryweight: '权重',
        academicdetail_text_vci: '查看分类',
        academicdetail_text_earnedpoint: '所获分数',
        academicdetail_text_earnedpercentage: '所获成绩',
        academicdetail_text_attendancereport: '出勤报告',
        academicdetail_text_categoryitems: '分类',
        studentlife_header: '学生生活',
        studentlife_text_participationhours: '课外活动小时数',
        studentlife_text_tpic: '当前总小时数',
        studentlife_text_qfce: '符合要求的职业教育小时数',
        studentlife_text_hrs: '小时',
        studentlife_text_pore: '户外体育活动',
        studentlife_text_aisd: '学术拓展',
        studentlife_text_cile: '领导力培养',
        studentlife_text_acle: '艺术拓展',
        studentlife_button_mcai: '我孩子的本学期活动',
        studentlife_button_asai: '学校本学期活动',
        studentlife_button_tphs: '小时数自',
        volunteerhours_header: '志愿活动小时数',
        volunteerhours_text_ceh: '职业教育小时数',
        volunteerhours_text_qfce: '符合要求的职业发展时数',
        volunteerhours_text_hrs: '小时',
        studentlifedetail_header: '学生生活详情',
        studentlifedetail_text_hrs: '小时',
        studentlifedetail_text_pore: '课外活动',
        studentlifedetail_text_aisd: '学术拓展',
        studentlifedetail_text_cile: '领导力培养',
        studentlifedetail_text_acle: '艺术拓展',
        mychildsactivities_header: '我孩子的活动',
        mychildsactivities_text_cua: '已完成/已注册活动',
        allactivities_header: '所有活动',
        allactivities_text_allactivities: '所有活动',
        activitydetail_header: '活动详情',
        activitydetail_text_teacher: '老师',
        activitydetail_text_eph: '所获小时数',
        activitydetail_text_vwe: '志愿活动',
        activitydetail_text_location: '地点',
        activitydetail_text_from: '从',
        activitydetail_text_to: '至',
        participationgraph_header: '活动图表',
        participationgraph_text_currentterm: '当前学期',
        participationgraph_text_totalhours: '总小时数',
        participationgraph_text_participationhours: '活动小时数',
        participationgraph_text_tph: '总活动小时数',
        participationgraph_text_since: '自',
        bodwellexplained_header: '关于博域',
        bodwellexplained_text_lab: '博域相关',
        bodwellexplained_text_avlt: '视频',
        bodwellexplained_text_academics: '学术',
        bodwellexplained_text_studentlife: '生活',
        bodwellexplained_text_video: '视频',
        bodwellexplainedlist_header: '关于博域',
        bodwellexplainedlist_text_academicsvideo: '学术视频',
        bodwellexplainedlist_text_slv: '生活视频',
        schoolcommunity_header: '校园社区',
        schoolcommunity_text_wgo: '博域进行时',
        schoolcommunity_text_ambb: '博域新鲜事随时更新',
        schoolcommunity_text_cd: '日历',
        schoolcommunity_text_biv: '视频',
        schoolcommunity_text_picturegallery: '图片',
        schoolcommunity_text_wvm: '每周视频简讯',
        schoolcommunity_text_staffinvolved: '相关教师',
        schoolcommunity_text_importantdocuments: '重要文件',
        calendar_header: '日历',
        bodwellinvideo_header: '博域视频',
        picturegallery_header: '图片',
        picturegallery_text_picturegallery: '图片',
        picturegallery_text_pavg: '实时更新博域最新视频及图片资料',
        picturegallery_text_campusphotos: '校园图片',
        picturegallery_text_studentlife: '学生生活',
        picturegallery_text_btw: '本周博域',
        picturegallery_text_bodwellbruins: '体育赛事',
        campusphotogallery_header: '校园照片',
        studentlifegallery_header: '学生生活',
        bodwellthisweekgallery_header: '本周博域',
        bodwellbruinsgallery_header: '博域体育',
        weeklyvideomessages_header: '每周视频简讯',
        weeklyvideomessagesdetail_text_wvm: '每周视频简讯',
        staffinvolved_header: '相关教师',
        staffinvolved_text_staffinvolved: '相关教师',
        staffinvolved_text_teachers: '老师',
        staffinvolved_text_sc: '周六课程及社团',
        staffinvolved_text_cya: '辅导&住宿老师',
        staffinvolved_text_principals: '校长',
        importantdocuments_header: '文件',
        importantdocuments_text_bsh: '博域学生手册',
        setting_text_language: '语言',
        setting_text_sypl: '在应用中设置首选语言',
    },
    zhHant: {
        term_text_tns: '學期未開始',
        term_text_fhot: '上半學期',
        term_text_shot: '下半學期',
        term_text_eot: '期終',
        error_text_nodata: '沒有數據',
        attendance_text_excused: '請假',
        attendance_text_nonexcused: '未請假',
        attendance_text_nurseroom: '校醫',
        attendance_text_sportsevent: '體育賽事',
        attendance_text_fieldtrip: '出遊',
        attendance_text_late: '遲到',
        attendance_text_absent: '缺勤',
        home_title: '主頁',
        message_title: '消息',
        academics_title: '學術',
        studentlife_title: '生活',
        bodwellexplained_title: '關於博域',
        schoolcommunity_title: '博域社區',
        setting_title: '設置',
        logout_title: '登出',
        home_header: '主頁',
        message_header: '消息',
        messagedetail_header: '消息',
        academics_header: '學術',
        academics_button_attendance: '出勤',
        attendance_header: '出勤',
        attendance_text_attendancereport: '出勤報告',
        academics_text_creditcourse: '學分課程',
        academics_text_teacher: '老師',
        academics_text_noncreditcourses: '非學分課程',
        academics_text_saturdayenrichment: '週六課程',
        academics_text_club: '社團',
        academicdetail_header: '學術信息',
        academicdetail_text_overallaverage: '總平均分',
        academicdetail_text_grade: '成績',
        academicdetail_text_teacher: '老師',
        academicdetail_text_categoryweight: '權重',
        academicdetail_text_vci: '查看分類',
        academicdetail_text_earnedpoint: '所獲分數',
        academicdetail_text_earnedpercentage: '所獲成績',
        academicdetail_text_attendancereport: '出勤報告',
        academicdetail_text_categoryitems: '分類',
        studentlife_header: '學生生活',
        studentlife_text_participationhours: '課外活動小時數',
        studentlife_text_tpic: '當前總小時數',
        studentlife_text_qfce: '符合要求的職業教育小時數',
        studentlife_text_hrs: '小時',
        studentlife_text_pore: '戶外體育活動',
        studentlife_text_aisd: '學術拓展',
        studentlife_text_cile: '領導力培養',
        studentlife_text_acle: '藝術拓展',
        studentlife_button_mcai: '我孩子的本學期活動',
        studentlife_button_asai: '學校本學期活動',
        studentlife_button_tphs: '小時數自',
        volunteerhours_header: '志願活動小時數',
        volunteerhours_text_ceh: '職業教育小時數',
        volunteerhours_text_qfce: '符合要求的職業發展時數',
        volunteerhours_text_hrs: '小時',
        studentlifedetail_header: '學生生活詳情',
        studentlifedetail_text_hrs: '小時',
        studentlifedetail_text_pore: '課外活動',
        studentlifedetail_text_aisd: '學術拓展',
        studentlifedetail_text_cile: '領導力培養',
        studentlifedetail_text_acle: '藝術拓展',
        mychildsactivities_header: '我孩子的活動',
        mychildsactivities_text_cua: '已完成/已註冊活動',
        allactivities_header: '所有活動',
        allactivities_text_allactivities: '所有活動',
        activitydetail_header: '活動詳情',
        activitydetail_text_teacher: '老師',
        activitydetail_text_eph: '所獲小時數',
        activitydetail_text_vwe: '志願活動',
        activitydetail_text_location: '地點',
        activitydetail_text_from: '從',
        activitydetail_text_to: '至',
        participationgraph_header: '活動圖表',
        participationgraph_text_currentterm: '當前學期',
        participationgraph_text_totalhours: '總小時數',
        participationgraph_text_participationhours: '活動小時數',
        participationgraph_text_tph: '總活動小時數',
        participationgraph_text_since: '自',
        bodwellexplained_header: '關於博域',
        bodwellexplained_text_lab: '博域相關',
        bodwellexplained_text_avlt: '視頻',
        bodwellexplained_text_academics: '學術',
        bodwellexplained_text_studentlife: '生活',
        bodwellexplained_text_video: '視頻',
        bodwellexplainedlist_header: '關於博域',
        bodwellexplainedlist_text_academicsvideo: '學術視頻',
        bodwellexplainedlist_text_slv: '生活視頻',
        schoolcommunity_header: '校園社區',
        schoolcommunity_text_wgo: '博域進行時',
        schoolcommunity_text_ambb: '博域新鮮事隨時更新',
        schoolcommunity_text_cd: '日曆',
        schoolcommunity_text_biv: '視頻',
        schoolcommunity_text_picturegallery: '圖片',
        schoolcommunity_text_wvm: '每週視頻簡訊',
        schoolcommunity_text_staffinvolved: '相關教師',
        schoolcommunity_text_importantdocuments: '重要文件',
        calendar_header: '日曆',
        bodwellinvideo_header: '博域視頻',
        picturegallery_header: '圖片',
        picturegallery_text_picturegallery: '圖片',
        picturegallery_text_pavg: '實時更新博域最新視頻及圖片資料',
        picturegallery_text_campusphotos: '校園圖片',
        picturegallery_text_studentlife: '學生生活',
        picturegallery_text_btw: '本周博域',
        picturegallery_text_bodwellbruins: '體育賽事',
        campusphotogallery_header: '校園照片',
        studentlifegallery_header: '學生生活',
        bodwellthisweekgallery_header: '本周博域',
        bodwellbruinsgallery_header: '博域體育',
        weeklyvideomessages_header: '每週視頻簡訊',
        weeklyvideomessagesdetail_text_wvm: '每週視頻簡訊',
        staffinvolved_header: '相關教師',
        staffinvolved_text_staffinvolved: '相關教師',
        staffinvolved_text_teachers: '老師',
        staffinvolved_text_sc: '週六課程及社團',
        staffinvolved_text_cya: '輔導&住宿老師',
        staffinvolved_text_principals: '校長',
        importantdocuments_header: '文件',
        importantdocuments_text_bsh: '博域學生手冊',
        setting_text_language: '語言',
        setting_text_sypl: '在應用中設置首選語言',

    },
    koKR: {
        term_text_tns: '학기 시작전',
        term_text_fhot: '학기 전반부 진행중',
        term_text_shot: '학기 후반부 진행중',
        term_text_eot: '학기 종료',
        error_text_nodata: '데이터 없음',
        attendance_text_excused: '사전 통보',
        attendance_text_nonexcused: '사전 미통보',
        attendance_text_nurseroom: '양호실',
        attendance_text_sportsevent: '스포츠 시합',
        attendance_text_fieldtrip: '운동 및 야외 활동',
        attendance_text_late: '지각',
        attendance_text_absent: '결석',
        home_title: '홈',
        message_title: '메세지',
        academics_title: '학사',
        studentlife_title: '학생 생활',
        bodwellexplained_title: '보드웰 설명',
        schoolcommunity_title: '학교 커뮤니티',
        setting_title: '설정',
        logout_title: '로그아웃',
        home_header: '홈',
        message_header: '메세지',
        messagedetail_header: '메세지',
        academics_header: '학사',
        academics_button_attendance: '출석',
        attendance_header: '출석',
        attendance_text_attendancereport: '출석 리포트',
        academics_text_creditcourse: '학점 이수 과목',
        academics_text_teacher: '교사',
        academics_text_noncreditcourses: '미학점 과목',
        academics_text_saturdayenrichment: '토요일 프로그램',
        academics_text_club: '클럽',
        academicdetail_header: '이수 과목',
        academicdetail_text_overallaverage: '전체 평균',
        academicdetail_text_grade: '학점',
        academicdetail_text_teacher: '교사',
        academicdetail_text_categoryweight: '가중치',
        academicdetail_text_vci: '평가 항목',
        academicdetail_text_earnedpoint: '가중치 포인트',
        academicdetail_text_earnedpercentage: '퍼센티지',
        academicdetail_text_attendancereport: '출결 리포트',
        academicdetail_text_categoryitems: '평가 항목',
        studentlife_header: '생활 활동',
        studentlife_text_participationhours: '활동 시간',
        studentlife_text_tpic: '이번 학기 누적',
        studentlife_text_qfce: '커리어 개발 누적',
        studentlife_text_hrs: '시간',
        studentlife_text_pore: '운동/야외 활동',
        studentlife_text_aisd: '학문/기술 개발',
        studentlife_text_cile: '시민의식/리더쉽',
        studentlife_text_acle: '예술/문화/지역탐험',
        studentlife_button_mcai: '우리아이 참가활동',
        studentlife_button_asai: '전체 프로그램 목록',
        studentlife_button_tphs: '누적 활동 시간',
        volunteerhours_header: '자원봉사 시간',
        volunteerhours_text_ceh: '커리어 개발 시간',
        volunteerhours_text_qfce: '커리어 개발 시간 인정',
        volunteerhours_text_hrs: '시간',
        studentlifedetail_header: '학생 생활 상세',
        studentlifedetail_text_hrs: '시간',
        studentlifedetail_text_pore: '운동/야외 활동',
        studentlifedetail_text_aisd: '학문/기술 개발',
        studentlifedetail_text_cile: '시민의식/리더쉽',
        studentlifedetail_text_acle: '예술/문화/지역탐험',
        mychildsactivities_header: '우리 아이 참가 활동',
        mychildsactivities_text_cua: '완료 및 예정 활동',
        allactivities_header: '모든 활동',
        allactivities_text_allactivities: '모든 활동',
        activitydetail_header: '액티비티 내용',
        activitydetail_text_teacher: '교사',
        activitydetail_text_eph: '인정된 참가 시간',
        activitydetail_text_vwe: '자원봉사 및 직업 훈련 시간',
        activitydetail_text_location: '장소',
        activitydetail_text_from: '발신',
        activitydetail_text_to: '수신',
        participationgraph_header: '액티비티 누적 그래프',
        participationgraph_text_currentterm: '이번 학기',
        participationgraph_text_totalhours: '전체 시간',
        participationgraph_text_participationhours: '참가 시간',
        participationgraph_text_tph: '전체 참가 시간',
        participationgraph_text_since: '이래',
        bodwellexplained_header: '보드웰 학교 설명',
        bodwellexplained_text_lab: '보드웰 학교 알아보기',
        bodwellexplained_text_avlt: '비디오 라이브러리',
        bodwellexplained_text_academics: '학사',
        bodwellexplained_text_studentlife: '학생 생활',
        bodwellexplained_text_video: '비디오',
        bodwellexplainedlist_header: '보드웰 학교 설명',
        bodwellexplainedlist_text_academicsvideo: '학사 관련 비디오',
        bodwellexplainedlist_text_slv: '학생 생활 관련 비디오',
        schoolcommunity_header: '학교 커뮤니티',
        schoolcommunity_text_wgo: '보드웰 학교 소식',
        schoolcommunity_text_ambb: '멀티미디어 게시판',
        schoolcommunity_text_cd: '학교 달력',
        schoolcommunity_text_biv: '보드웰 비디오',
        schoolcommunity_text_picturegallery: '사진 갤러리',
        schoolcommunity_text_wvm: '주간 비디오 메세지',
        schoolcommunity_text_staffinvolved: '학교 직원',
        schoolcommunity_text_importantdocuments: '중요 문서',
        calendar_header: '달력',
        bodwellinvideo_header: '비디오',
        picturegallery_header: '사진 갤러리',
        picturegallery_text_picturegallery: '사진 갤러리',
        picturegallery_text_pavg: '사진 및 비디오 갤러리',
        picturegallery_text_campusphotos: '학교 시설',
        picturegallery_text_studentlife: '학생 생활',
        picturegallery_text_btw: '보드웰 주간',
        picturegallery_text_bodwellbruins: '보드웰 스포츠팀',
        campusphotogallery_header: '캠퍼스 사진',
        studentlifegallery_header: '학생 생활 사진',
        bodwellthisweekgallery_header: '이번주 보드웰',
        bodwellbruinsgallery_header: '보드웰 스포츠팀',
        weeklyvideomessages_header: '주간 비디오 메세지',
        weeklyvideomessagesdetail_text_wvm: '주간 비디오 메세지',
        staffinvolved_header: '관련 직원',
        staffinvolved_text_staffinvolved: '관련 직원',
        staffinvolved_text_teachers: '교사',
        staffinvolved_text_sc: '토요수업 및 클럽 지도교사',
        staffinvolved_text_cya: '카운셀러 및 ',
        staffinvolved_text_principals: '교장',
        importantdocuments_header: '문서',
        importantdocuments_text_bsh: '보드웰 학생 핸드북',
        setting_text_language: '언어',
        setting_text_sypl: '원하는 언어를 설정하십시오',
    },
    ru: {
        term_text_tns: 'Срок не начался',
        term_text_fhot: 'Первая половина семестра в процессе',
        term_text_shot: 'Вторая половина семестра в процессе',
        term_text_eot: 'Конец срока',
        error_text_nodata: 'Нет данных',
        attendance_text_excused: 'извинить',
        attendance_text_nonexcused: 'Non-извинившись',
        attendance_text_nurseroom: 'Комната для медсестер',
        attendance_text_sportsevent: 'Спортивное мероприятие',
        attendance_text_fieldtrip: 'Экскурсия',
        attendance_text_late: 'поздно',
        attendance_text_absent: 'Отсутствует',
        home_title: 'Дом',
        message_title: 'Сообщение',
        academics_title: 'Академики',
        studentlife_title: 'Студенческая жизнь',
        bodwellexplained_title: 'Бодвелл объяснил',
        schoolcommunity_title: 'Школьное Сообщество',
        setting_title: 'настройки',
        logout_title: 'Выйти',
        home_header: 'Дом',
        message_header: 'Сообщение',
        messagedetail_header: 'Сообщение',
        academics_header: 'Академики',
        attendance_header: 'присутствие',
        academicdetail_header: 'Академическая деталь',
        studentlife_header: 'Студенческая жизнь',
        volunteerhours_header: 'Волонтерские Часы',
        studentlifedetail_header: 'Студенческая жизнь Подробнее',
        mychildsactivities_header: 'Деятельность моего ребенка',
        allactivities_header: 'Все мероприятия',
        activitydetail_header: 'Подробности деятельности',
        participationgraph_header: 'График участия',
        bodwellexplained_header: 'Бодвелл объяснил',
        bodwellexplainedlist_header: 'Бодвелл объяснил',
        schoolcommunity_header: 'Школьное Сообщество',
        calendar_header: 'Календарь',
        bodwellinvideo_header: 'Bodwell в видео',
        picturegallery_header: 'Картинная галерея',
        campusphotogallery_header: 'Кампус Фото',
        studentlifegallery_header: 'Студенческая жизнь',
        bodwellthisweekgallery_header: 'Бодвелл на этой неделе',
        bodwellbruinsgallery_header: 'Бодвелл Брюинз',
        weeklyvideomessages_header: 'Еженедельные видео сообщения',
        staffinvolved_header: 'Вовлеченный персонал',
        importantdocuments_header: 'документы',
        setting_text_language: 'язык',
        setting_text_sypl: 'Установите предпочитаемый язык в приложении',
    },
    es: {
        term_text_tns: 'Término no iniciado',
        term_text_fhot: 'Primer semestre en curso',
        term_text_shot: 'Segundo semestre en curso',
        term_text_eot: 'Fin de los términos',
        error_text_nodata: 'Sin datos',
        attendance_text_excused: 'Excusado',
        attendance_text_nonexcused: 'No excusado',
        attendance_text_nurseroom: 'Sala de enfermería',
        attendance_text_sportsevent: 'Evento deportivo',
        attendance_text_fieldtrip: 'Viaje de estudios',
        attendance_text_late: 'Tarde',
        attendance_text_absent: 'Ausente',
        home_title: 'Hogar',
        message_title: 'Mensaje',
        academics_title: 'Académico',
        studentlife_title: 'Vida de estudiante',
        bodwellexplained_title: 'Bodwell explicado',
        schoolcommunity_title: 'Comunidad escolar',
        setting_title: 'Configuraciones',
        logout_title: 'Cerrar sesión',
        home_header: 'Hogar',
        message_header: 'Mensaje',
        messagedetail_header: 'Mensaje',
        academics_header: 'Académico',
        attendance_header: 'Asistencia',
        academicdetail_header: 'Detalle Académico',
        studentlife_header: 'Vida de estudiante',
        volunteerhours_header: 'Horas de voluntariado',
        studentlifedetail_header: 'Detalle de la vida estudiantil',
        mychildsactivities_header: 'Las actividades de mi hijo',
        allactivities_header: 'Todas las actividades',
        activitydetail_header: 'Detalle de actividad',
        participationgraph_header: 'Gráfico de participación',
        bodwellexplained_header: 'Bodwell explicado',
        bodwellexplainedlist_header: 'Bodwell explicado',
        schoolcommunity_header: 'Comunidad escolar',
        calendar_header: 'Calendario',
        bodwellinvideo_header: 'Bodwell en video',
        picturegallery_header: 'Galería de imágenes',
        campusphotogallery_header: 'Foto del campus',
        studentlifegallery_header: 'Vida de estudiante',
        bodwellthisweekgallery_header: 'Bodwell esta semana',
        bodwellbruinsgallery_header: 'Bodwell Bruins',
        weeklyvideomessages_header: 'Mensajes de video semanales',
        staffinvolved_header: 'Personal involucrado',
        importantdocuments_header: 'Documentos',
        setting_text_language: 'Idioma',
        setting_text_sypl: 'Establece tu idioma preferido en la aplicación',
    },
    ar: {
        term_text_tns: 'مصطلح لم يبدأ',
        term_text_fhot: 'النصف الأول من الفصل في التقدم',
        term_text_shot: 'النصف الثاني من الفصل في التقدم',
        term_text_eot: 'نهاية الفصل الدراسي',
        error_text_nodata: 'لايوجد بيانات',
        attendance_text_excused: 'معذور',
        attendance_text_nonexcused: 'غير معذور',
        attendance_text_nurseroom: 'غرفة ممرضة',
        attendance_text_sportsevent: 'حدث رياضي',
        attendance_text_fieldtrip: 'رحلة ميدانية',
        attendance_text_late: 'متأخر',
        attendance_text_absent: 'غائب',
        home_title: 'الصفحة الرئيسية',
        message_title: 'رسالة',
        academics_title: 'أكاديميون',
        studentlife_title: 'الحياة الطلابية',
        bodwellexplained_title: 'وأوضح بودويل',
        schoolcommunity_title: 'مجتمع المدرسة',
        setting_title: 'الإعدادات',
        logout_title: 'تسجيل خروج',
        home_header: 'الصفحة الرئيسية',
        message_header: 'رسالة',
        messagedetail_header: 'رسالة',
        academics_header: 'أكاديميون',
        attendance_header: 'الحضور',
        academicdetail_header: 'التفاصيل الأكاديمية',
        studentlife_header: 'الحياة الطلابية',
        volunteerhours_header: 'ساعات التطوع',
        studentlifedetail_header: 'تفاصيل حياة الطالب',
        mychildsactivities_header: 'أنشطة طفلي',
        allactivities_header: 'كل الأنشطة',
        activitydetail_header: 'تفاصيل النشاط',
        participationgraph_header: 'الرسم البياني المشاركة',
        bodwellexplained_header: 'وأوضح بودويل',
        bodwellexplainedlist_header: 'وأوضح بودويل',
        schoolcommunity_header: 'مجتمع المدرسة',
        calendar_header: 'التقويم',
        bodwellinvideo_header: 'بودويل في الفيديو',
        picturegallery_header: 'معرض صور',
        campusphotogallery_header: 'صور الحرم الجامعي',
        studentlifegallery_header: 'الحياة الطلابية',
        bodwellthisweekgallery_header: 'بودويل هذا الأسبوع',
        bodwellbruinsgallery_header: 'بودويل بروينس',
        weeklyvideomessages_header: 'رسائل الفيديو الأسبوعية',
        staffinvolved_header: 'الموظفين المعنيين',
        importantdocuments_header: 'مستندات',
        setting_text_language: 'لغة',
        setting_text_sypl: 'اضبط لغتك المفضلة في التطبيق',
    },
    fa: {
        term_text_tns: 'مدت شروع نشده است',
        term_text_fhot: 'نیمه اول ترم در حال انجام است',
        term_text_shot: 'نیمه دوم ترم در حال انجام است',
        term_text_eot: 'پایان ترم',
        error_text_nodata: 'اطلاعاتی وجود ندارد',
        attendance_text_excused: 'بهانه',
        attendance_text_nonexcused: 'غیر معذور',
        attendance_text_nurseroom: 'اتاق پرستار',
        attendance_text_sportsevent: 'رویداد ورزشی',
        attendance_text_fieldtrip: 'گردش علمی',
        attendance_text_late: 'دیر',
        attendance_text_absent: 'غایب',
        home_title: 'خانه',
        message_title: 'پیام',
        academics_title: 'دانشگاهیان',
        studentlife_title: 'زندگی دانشجویی',
        bodwellexplained_title: 'بدول توضیح داد',
        schoolcommunity_title: 'جامعه مدرسه',
        setting_title: 'تنظیمات',
        logout_title: 'خروج',
        home_header: 'خانه',
        message_header: 'پیام',
        messagedetail_header: 'پیام',
        academics_header: 'دانشگاهیان',
        attendance_header: 'حضور',
        academicdetail_header: 'جزئیات دانشگاهی',
        studentlife_header: 'زندگی دانشجویی',
        volunteerhours_header: 'ساعات داوطلبانه',
        studentlifedetail_header: 'جزئیات زندگی دانشجویی',
        mychildsactivities_header: 'فعالیت های فرزند من',
        allactivities_header: 'همه فعالیت ها',
        activitydetail_header: 'جزئیات فعالیت',
        participationgraph_header: 'نمودار مشارکت',
        bodwellexplained_header: 'بدول توضیح داد',
        bodwellexplainedlist_header: 'بدول توضیح داد',
        schoolcommunity_header: 'جامعه مدرسه',
        calendar_header: 'تقویم',
        bodwellinvideo_header: 'بدول در فیلم',
        picturegallery_header: 'گالری تصاویر',
        campusphotogallery_header: 'عکس پردیس',
        studentlifegallery_header: 'زندگی دانشجویی',
        bodwellthisweekgallery_header: 'بدول این هفته',
        bodwellbruinsgallery_header: 'بدول بروجین',
        weeklyvideomessages_header: 'پیام های ویدیویی هفتگی',
        staffinvolved_header: 'کارمندان درگیر شدند',
        importantdocuments_header: 'اسناد',
        setting_text_language: 'زبان',
        setting_text_sypl: 'زبان دلخواه خود را در برنامه تنظیم کنید',
    },
    vi: {
        term_text_tns: 'Học kỳ chưa bắt đầu',
        term_text_fhot: 'Đang trong nửa học kỳ đầu',
        term_text_shot: 'Đang trong nửa học kỳ sau',
        term_text_eot: 'Kết thúc học kỳ',
        error_text_nodata: 'Chưa có thông tin',
        attendance_text_excused: 'Có phép',
        attendance_text_nonexcused: 'Không phép',
        attendance_text_nurseroom: 'Phòng y tế',
        attendance_text_sportsevent: 'Sự kiện thể thao',
        attendance_text_fieldtrip: 'Chuyến đi thực tế',
        attendance_text_late: 'Trễ',
        attendance_text_absent: 'Vắng',
        home_title: 'Nhà',
        message_title: 'Tin nhắn',
        academics_title: 'Học thuật',
        studentlife_title: 'Đời sống',
        bodwellexplained_title: 'Bodwell diễn giải',
        schoolcommunity_title: 'Cộng đồng',
        setting_title: 'Cài đặt',
        logout_title: 'Đăng xuất',
        home_header: 'Nhà',
        message_header: 'Tin nhắn',
        messagedetail_header: 'Chi tiết tin nhắn',
        academics_header: 'Học thuật',
        academics_button_attendance: 'Điểm danh',
        attendance_header: 'Điểm danh',
        attendance_text_attendancereport: 'Báo cáo chuyên cần',
        academics_text_creditcourse: 'Tín chỉ môn học',
        academics_text_teacher: 'Giáo viên',
        academics_text_noncreditcourses: 'Môn học không tín chỉ',
        academics_text_saturdayenrichment: 'Lớp học thứ bảy ',
        academics_text_club: 'Câu lạc bộ',
        academicdetail_header: 'Chi tiết học lực',
        academicdetail_text_overallaverage: 'Trung bình các môn',
        academicdetail_text_grade: 'Lớp',
        academicdetail_text_teacher: 'GIÁO VIÊN',
        academicdetail_text_categoryweight: 'Phân loại đánh giá',
        academicdetail_text_vci: 'Xem phân loại chi tiết',
        academicdetail_text_earnedpoint: 'Điểm tích lũy',
        academicdetail_text_earnedpercentage: 'Phần trăm tích lũy',
        academicdetail_text_attendancereport: 'Báo cáo chuyên cần',
        academicdetail_text_categoryitems: 'Phân loại chi tiết',
        studentlife_header: 'Đời sống học sinh',
        studentlife_text_participationhours: 'Số giờ tham gia',
        studentlife_text_tpic: 'Tổng tham gia trong học kỳ hiện tại',
        studentlife_text_qfce: 'Đủ tiêu chuẩn định hướng nghề nghiệp',
        studentlife_text_hrs: 'Giờ',
        studentlife_text_pore: 'Giáo dục thể chất và thể thao ngoài trời',
        studentlife_text_aisd: 'Học thuật, sở thích và kỹ năng phát triển',
        studentlife_text_cile: 'Trách nhiệm công dân, tương tác và lãnh đạo',
        studentlife_text_acle: 'Nghệ thuật, văn hóa và khám phá bản địa',
        studentlife_button_mcai: 'Hoạt động của con tôi',
        studentlife_button_asai: 'Hoạt động của trường',
        studentlife_button_tphs: 'Tổng số giờ tham gia hoạt động từ',
        volunteerhours_header: 'Số giờ tình nguyện',
        volunteerhours_text_ceh: 'Số giờ khám phá nghề nghiệp',
        volunteerhours_text_qfce: 'Đủ tiêu chuẩn định hướng nghề nghiệp',
        volunteerhours_text_hrs: 'Giờ',
        studentlifedetail_header: 'Chi tiết đời sống học sinh',
        studentlifedetail_text_hrs: 'Giờ',
        studentlifedetail_text_pore: 'Giáo dục thể chất và thể thao ngoài trời',
        studentlifedetail_text_aisd: 'Học thuật, sở thích và kỹ năng phát triển',
        studentlifedetail_text_cile: 'Trách nhiệm công dân, tương tác và lãnh đạo',
        studentlifedetail_text_acle: 'Nghệ thuật, văn hóa và khám phá bản địa',
        mychildsactivities_header: 'Hoạt động của con tôi',
        mychildsactivities_text_cua: 'Đã hoàn thành/ hoạt động sắp tới',
        allactivities_header: 'Tất cả hoạt động',
        allactivities_text_allactivities: 'Tất cả hoạt động',
        activitydetail_header: 'Chi tiết hoạt động',
        activitydetail_text_teacher: 'GIÁO VIÊN',
        activitydetail_text_eph: 'Tich lũy số giờ tham gia',
        activitydetail_text_vwe: 'Tình nguyện viên và Kinh nghiệm làm việc',
        activitydetail_text_location: 'Địa điểm',
        activitydetail_text_from: 'Từ',
        activitydetail_text_to: 'Đến',
        participationgraph_header: 'Biểu đồ tham gia',
        participationgraph_text_currentterm: 'Học kỳ hiện tại',
        participationgraph_text_totalhours: 'Tổng giờ',
        participationgraph_text_participationhours: 'Số giờ tham gia',
        participationgraph_text_tph: 'Tổng số giờ tham gia',
        participationgraph_text_since: 'Từ lúc',
        bodwellexplained_header: 'Diễn giải của Bodwell',
        bodwellexplained_text_lab: 'Hiểu về Bodwell',
        bodwellexplained_text_avlt: 'Thư viện video giúp trả lời vài hoặc đa số câu hỏi thường gặp.',
        bodwellexplained_text_academics: 'Học thuật',
        bodwellexplained_text_studentlife: 'Đời sống học sinh',
        bodwellexplained_text_video: 'Video',
        bodwellexplainedlist_header: 'Diễn giải của Bodwell',
        bodwellexplainedlist_text_academicsvideo: 'Video về học thuật',
        bodwellexplainedlist_text_slv: 'Video về đời sống học sinh',
        schoolcommunity_header: 'Cộng đồng trường',
        schoolcommunity_text_wgo: 'Điều gì tiếp theo?',
        schoolcommunity_text_ambb: 'Bảng tin đa phương tiện giúp bạn cập nhật những sự kiện đang diễn ra tại Bodwell',
        schoolcommunity_text_cd: 'Lịch & Những ngày đáng chú ý',
        schoolcommunity_text_biv: 'Bodwell bằng Video',
        schoolcommunity_text_picturegallery: 'Thư viện hình ảnh',
        schoolcommunity_text_wvm: 'Thông điệp video hàng tuần',
        schoolcommunity_text_staffinvolved: 'Nhân viên tham gia',
        schoolcommunity_text_importantdocuments: 'Văn bản quan trọng',
        calendar_header: 'Lịch',
        bodwellinvideo_header: 'Bodwell bằng Video',
        picturegallery_header: 'Thư viện hình ảnh',
        picturegallery_text_picturegallery: 'THƯ VIỆN HÌNH ẢNH',
        picturegallery_text_pavg: 'Hình ảnh và thư viện video về khuôn viên trường và các hoạt động tại Boadwell. Kiểm tra thường xuyên để cập nhật thông tin mới!',
        picturegallery_text_campusphotos: 'HÌNH ẢNH KHUÔN VIÊN TRƯỜNG',
        picturegallery_text_studentlife: 'ĐỜI SỐNG HỌC SINH',
        picturegallery_text_btw: 'Bodwell tuần qua',
        picturegallery_text_bodwellbruins: 'THỂ THAO BOODWELL',
        campusphotogallery_header: 'Hình ảnh khuôn viên trường',
        studentlifegallery_header: 'Đời sống học sinh',
        bodwellthisweekgallery_header: 'Bodwell tuần qua',
        bodwellbruinsgallery_header: 'Thể thao Bodwell',
        weeklyvideomessages_header: 'Video thông điệp hàng tuần',
        weeklyvideomessagesdetail_text_wvm: 'Video thông điệp hàng tuần',
        staffinvolved_header: 'Nhân viên phụ trách',
        staffinvolved_text_staffinvolved: 'Nhân viên phụ trách',
        staffinvolved_text_teachers: 'Giáo viên',
        staffinvolved_text_sc: 'Lớp học thứ bảy và Câu lạc bộ',
        staffinvolved_text_cya: 'Cố vấn & cố vấn thanh niên',
        staffinvolved_text_principals: 'Hiệu trưởng',
        importantdocuments_header: 'Văn bản',
        importantdocuments_text_bsh: 'Cẩm nang học sinh Bodwell',
        setting_text_language: 'Ngôn ngữ',
        setting_text_sypl: 'Đặt ngôn ngữ ưa thích của bạn trong ứng dụng',
    }
};

export function translate(word) {
    return i18n.t(word)
}